---
version: "2.1"
services:
  tvheadend:
    image: lscr.io/linuxserver/tvheadend:latest
    container_name: tvheadend
    environment:
      - PUID=1002
      - PGID=100
      - TZ=Europe/London
      - RUN_OPTS= #optional
    volumes:
      - /share/CACHEDEV1_DATA/Containers/tvheadend/config:/config
      - /share/CACHEDEV1_DATA/Containers/tvheadend/recordings:/recordings
    ports:
      - 9981:9981
      - 9982:9982
    devices:
      - /dev/dri:/dev/dri #optional
      - /dev/dvb:/dev/dvb #optional
    restart: unless-stopped