version: "3"
services:
  plex:
    container_name: plexv2
    image: lscr.io/linuxserver/plex:latest
    restart: on-failure
    env_file: .env
    network_mode: host  # Keeping host mode for local network discovery
    volumes:
      - /share/CACHEDEV1_DATA/Containers/plex/Config:/config
      - /share/CACHEDEV1_DATA/Containers/plex/transcode:/transcode
      - /share/CACHEDEV1_DATA/Containers/plex/backups:/backups
      - /share/CACHEDEV2_DATA/Photo/Tv:/Tv
      - /share/CACHEDEV2_DATA/Photo/Kids TV:/kidstv
      - /share/CACHEDEV1_DATA/PLEX/movies:/movies 
      - /share/CACHEDEV2_DATA/Photo/Kids:/kidsmovies 
      - /share/CACHEDEV2_DATA/Photo/xmas:/xmasmovies 
      - /share/CACHEDEV2_DATA/Photo/Home Movies:/homemovies
      - /share/CACHEDEV2_DATA/Photo/Photos:/photos
      - /share/CACHEDEV2_DATA/Photo/Music:/music
    ports:
      - 32400:32400
    labels:
      - "nginx_proxy.enable=true"
      - "nginx_proxy.domain=plex.alexlovett.co.uk"
      - "nginx_proxy.ssl=true"
