---
version: "2.1"
services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1002
      - PGID=100
      - TZ=Europe/London
    volumes:
      - /Containers/prowlarr/config:/config 
      - /Containers/prowlarr/Queued:/downloads 
    ports:
      - 9696:9696
    restart: unless-stopped