version: "3"
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarrv2
    env_file: .env
    volumes:
      - /share/CACHEDEV1_DATA/Containers/radarr/config:/config
      - /share/CACHEDEV1_DATA/PLEX/movies:/movies 
      - /share/CACHEDEV2_DATA/Photo/movies:/movies2 
      - /share/CACHEDEV2_DATA/Photo/Kids:/kidsmovies
      - /share/CACHEDEV2_DATA/Photo/xmas:/xmasmovies 
      - /share/CACHEDEV1_DATA/Containers/downloads:/downloads 
    labels:
      - "nginx_proxy.enable=true"
      - "nginx_proxy.domain=radarr.alexlovett.co.uk"
      - "nginx_proxy.ssl=true"
    restart: on-failure
    networks:
      - media_network
  
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarrv2
    env_file: .env
    volumes:
      - /share/CACHEDEV1_DATA/Containers/Sonarr/config:/config
      - /share/CACHEDEV2_DATA/Photo/Tv:/tv
      - /share/CACHEDEV2_DATA/Photo/Kids TV:/kidstv
      - /share/CACHEDEV1_DATA/Containers/downloads:/downloads 
    labels:
      - "nginx_proxy.enable=true"
      - "nginx_proxy.domain=sonarr.alexlovett.co.uk"
      - "nginx_proxy.ssl=true"
    restart: on-failure
    networks:
      - media_network
    
  lidarr:
    image: linuxserver/lidarr:latest
    container_name: lidarrv2
    env_file: .env
    volumes:
      - /share/CACHEDEV1_DATA/Containers/lidarr/config:/config
      - /share/CACHEDEV2_DATA/Photo/Music:/music
      - /share/CACHEDEV1_DATA/Containers/downloads:/downloads
    labels:
      - "nginx_proxy.enable=true"
      - "nginx_proxy.domain=lidarr.alexlovett.co.uk"
      - "nginx_proxy.ssl=true"
    restart: on-failure
    networks:
      - media_network

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarrv2
    env_file: .env
    volumes:
      - /share/CACHEDEV1_DATA/Containers/prowlarr/config:/config 
      - /share/CACHEDEV1_DATA/Containers/prowlarr/Queued:/downloads 
    labels:
      - "nginx_proxy.enable=true"
      - "nginx_proxy.domain=prowlarr.alexlovett.co.uk"
      - "nginx_proxy.ssl=true"
    restart: unless-stopped
    networks:
      - media_network

  whisparr:
    image: hotio/whisparr:latest
    container_name: whisparr
    env_file: .env
    volumes:
      - /share/CACHEDEV1_DATA/Containers/whisparr/config:/config 
      - /share/CACHEDEV1_DATA/Containers/downloads:/downloads 
      - /share/CACHEDEV1_DATA/PLEX/tech:/tech
    labels:
      - "nginx_proxy.enable=true"
      - "nginx_proxy.domain=whisparr.alexlovett.co.uk"
      - "nginx_proxy.ssl=true"
    restart: unless-stopped
    networks:
      - media_network

networks:
  media_network:
    external: true
