version: "3.8"
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1002
      - PGID=100
      - TZ=Europe/London
    volumes:
      - /share/CACHEDEV1_DATA/Containers/radarr/config:/config
      - /share/CACHEDEV1_DATA/PLEX/movies:/movies 
      - /share/CACHEDEV2_DATA/Photo/movies:/movies2 
      - /share/CACHEDEV2_DATA/Photo/Kids:/kidsmovies
      - /share/CACHEDEV2_DATA/Photo/xmas:/xmasmovies 
      - /share/CACHEDEV1_DATA/Containers/downloads/usenet:/downloads
    expose: 
      - "7878"
    restart: unless-stopped
    networks:
      - media_network

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1002
      - PGID=100
      - TZ=Europe/London
    volumes:
      - /share/CACHEDEV1_DATA/Containers/Sonarr/config:/config
      - /share/CACHEDEV2_DATA/Photo/Tv:/tv
      - "/share/CACHEDEV2_DATA/Photo/Kids TV:/kidstv"
      - /share/CACHEDEV1_DATA/PLEX/samtv:/samtv 
      - /share/CACHEDEV1_DATA/Containers/downloads/usenet:/downloads
    expose:
      - "8989"
    restart: unless-stopped
    networks:
      - media_network

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1002
      - PGID=100
      - TZ=Europe/London
    volumes:
      - /share/CACHEDEV1_DATA/Containers/lidarr/config:/config
      - /share/CACHEDEV2_DATA/Photo/Music:/music
      - /share/CACHEDEV1_DATA/Containers/downloads/usenet:/downloads
    expose:
      - "8686"
    restart: unless-stopped
    networks:
      - media_network

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1002
      - PGID=100
      - TZ=Europe/London
    volumes:
      - /share/CACHEDEV1_DATA/Containers/prowlarr/config:/config 
      - /share/CACHEDEV1_DATA/Containers/prowlarr/Queued:/downloads 
    expose:
      - "9696"
    restart: unless-stopped
    networks:
      - media_network

networks:
  media_network:
    external: true