version: "3"

services:
  nzbget:
    image: lscr.io/linuxserver/nzbget:latest
    container_name: nzbgetv2
    environment:
      - PUID=1002
      - PGID=100
      - TZ=Europe/London
    volumes:
      - /share/CACHEDEV1_DATA/Containers/NZBGet/Config:/config
      - /share/CACHEDEV1_DATA/Containers/downloads/usenet:/downloads
      - /share/CACHEDEV1_DATA/PLEX:/data
      - /share/CACHEDEV1_DATA/PLEX/tech:/tech
    expose:
      - "6789"
    restart: unless-stopped
    networks:
      - media_network

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbdv2
    environment:
      - PUID=1002
      - PGID=100
      - TZ=Europe/London
    volumes:
      - /share/CACHEDEV1_DATA/Containers/sabnzbd/Config:/config
      - /share/CACHEDEV1_DATA/Containers/downloads/usenet:/downloads
      - /share/CACHEDEV1_DATA/Containers/downloads/usenet/intermediate:/incomplete-downloads
      - /share/CACHEDEV1_DATA/PLEX/tech:/tech
    expose:
      - "6800"
    restart: unless-stopped
    networks:
      - media_network

  hydra2:
    image: lscr.io/linuxserver/nzbhydra2:latest
    container_name: hydra2v2
    environment:
      - PUID=1002
      - PGID=100
      - TZ=Europe/London
    volumes:
      - /share/CACHEDEV1_DATA/Containers/Hydra2/config:/config
      - /share/CACHEDEV1_DATA/Containers/downloads:/downloads
    expose:
      - "5076"
    restart: unless-stopped
    networks:
      - media_network

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackettv2
    environment:
      - PUID=1002
      - PGID=100
      - TZ=Europe/London
      - AUTO_UPDATE=true
    volumes:
      - /share/CACHEDEV1_DATA/Containers/jackett/config:/config
      - /share/CACHEDEV1_DATA/Containers/downloads/torrents:/downloads
    expose:
      - "9117"
    restart: unless-stopped
    networks:
      - media_network

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrentv2
    environment:
      - PUID=1002
      - PGID=100
      - TZ=Europe/London
      - WEBUI_PORT=8080
    volumes:
      - /share/CACHEDEV1_DATA/Containers/qbittorrent/config:/config
      - /share/CACHEDEV1_DATA/Containers/downloads/torrents:/downloads
      - /share/CACHEDEV1_DATA/Containers/qbittorrent/watch:/watch
    expose:
      - "8080"
      - "6881"
      - "6881/udp"
    restart: unless-stopped
    networks:
      - media_network

  deemix:
    image: registry.gitlab.com/bockiii/deemix-docker:latest
    container_name: deemixv2
    environment:
      - PUID=1002
      - PGID=100
      - UMASK_SET=022
      - DEEMIX_SINGLE_USER=true
    volumes:
      - /share/CACHEDEV2_DATA/Photo/Music/deemix:/downloads
      - /share/CACHEDEV1_DATA/Containers/deemix/config:/config
    expose:
      - "6595"
    restart: unless-stopped
    networks:
      - media_network

networks:
  media_network:
    external: true

 
