---
services:
  nzbget:
    image: lscr.io/linuxserver/nzbget:latest
    container_name: nzbgetv2
    env_file: .env
    volumes:
      - /share/CACHEDEV1_DATA/Containers/NZBGet/Config:/config
      - /share/CACHEDEV1_DATA/Containers/downloads/usenet:/downloads
      - /share/CACHEDEV1_DATA/PLEX:/data
      - /share/CACHEDEV1_DATA/PLEX/tech:/tech
    labels:
      - "nginx_proxy.enable=true"
      - "nginx_proxy.domain=nzbget.alexlovett.co.uk"
      - "nginx_proxy.ssl=true"
    restart: on-failure
    networks:

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    env_file: .env
    volumes:
      - /share/CACHEDEV1_DATA/Containers/sabnzbd/Config:/config
      - /share/CACHEDEV1_DATA/Containers/downloads/usenet:/downloads
      - /share/CACHEDEV1_DATA/Containers/downloads/usenet/intermediate:/incomplete-downloads
      - /share/CACHEDEV1_DATA/PLEX/tech:/tech
    labels:
      - "nginx_proxy.enable=true"
      - "nginx_proxy.domain=sabnzbd.alexlovett.co.uk"
      - "nginx_proxy.ssl=true"
    restart: unless-stopped
    networks:

  hydra2:
    image: linuxserver/nzbhydra2:latest
    container_name: hydra2v2
    env_file: .env
    volumes:
      - /share/CACHEDEV1_DATA/Containers/Hydra2/config:/config
      - /share/CACHEDEV1_DATA/Containers/downloads:/downloads
    labels:
      - "nginx_proxy.enable=true"
      - "nginx_proxy.domain=hydra2.alexlovett.co.uk"
      - "nginx_proxy.ssl=true"
    restart: on-failure
    networks:

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackettv2
    env_file: .env
    volumes:
      - /share/CACHEDEV1_DATA/Containers/jackett/config:/config
      - /share/CACHEDEV1_DATA/Containers/downloads/torrents:/downloads
    labels:
      - "nginx_proxy.enable=true"
      - "nginx_proxy.domain=jackett.alexlovett.co.uk"
      - "nginx_proxy.ssl=true"
    restart: on-failure
    networks:

