---
version: "3"
services:
  nzbget:
    image: lscr.io/linuxserver/nzbget:latest
    container_name: nzbgetv2
    environment:
      - PUID=1002
      - PGID=100
      - TZ=Europe/London
    volumes:
      - /share/CACHEDEV1_DATA/Containers/NZBGet/Config:/config
      - /share/CACHEDEV1_DATA/Containers/downloads/usenet:/downloads
      - /share/CACHEDEV1_DATA/PLEX:/data
    ports:
      - 6789:6789
    restart: on-failure
    network_mode: host
    
  hydra2:
      image: linuxserver/nzbhydra2:latest
      container_name: hydra2v2
      environment:
      - PUID=1002
      - PGID=100
      - TZ=Europe/London
      volumes:
      - /share/CACHEDEV1_DATA/Containers/Hydra2/config:/config
      - /share/CACHEDEV1_DATA/Containers/downloads:/downloads
      ports:
      - 5076:5076
      restart: on-failure
      network_mode: host 

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackettv2
    environment:
      - PUID=1002
      - PGID=100
      - TZ=Europe/London
      - AUTO_UPDATE=true #optional
      - RUN_OPTS=<run options here> #optional
    volumes:
      - /share/CACHEDEV1_DATA/Containers/jackett/config:/config
      - /share/CACHEDEV1_DATA/Containers/downloads/torrents:/downloads
    ports:
      - 9117:9117
    restart: on-failure
    network_mode: host

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrentv2
    environment:
      - PUID=1002
      - PGID=100
      - TZ=Europe/London
      - WEBUI_PORT=8080
    volumes:
      - /share/CACHEDEV1_DATA/Containers/qbitorrent/config:/config
      - /share/CACHEDEV1_DATA/Containers/downloads/torrents:/downloads
      - /share/CACHEDEV1_DATA/Containers/qbitorrent/watch:/watch
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8181:8181
    restart: on-failure
    network_mode: host
  
  deemix:
    image: registry.gitlab.com/bockiii/deemix-docker
    container_name: Deemix
    volumes:
      - /share/CACHEDEV2_DATA/Photo/Music/deemix:/downloads
      - /share/CACHEDEV1_DATA/Containers/deemix/config:/config
    environment:
      - PUID=1002
      - PGID=100
      - UMASK_SET=022
      - DEEMIX_SINGLE_USER=true
    ports:
      - 6595:6595
    network_mode: host

 
