x-common-attributes: &common-attributes
  restart: unless-stopped

services:
  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    image: 'jc21/nginx-proxy-manager:latest'
    <<: *common-attributes
    env_file: .env
    networks:
      - media_network
    ports:
      - "80:80"      # HTTP
      - "443:443"    # HTTPS
      - "81:81"      # Admin UI
    volumes:
      - /share/CACHEDEV1_DATA/Containers/nginx-proxy-manager/data:/data
      - /share/CACHEDEV1_DATA/Containers/nginx-proxy-manager/letsencrypt:/etc/letsencrypt

  uptime-kuma:
    container_name: uptime-kuma
    hostname: uptime-kuma
    image: louislam/uptime-kuma:latest
    volumes:
    - /share/CACHEDEV1_DATA/Containers/uptime-kuma:/app/data
    - /var/run/docker.sock:/var/run/docker.sock
    expose:
    - "3001"
    networks:
      - media_network
    restart: unless-stopped

networks:
  media_network:
    external: true





