x-common-attributes: &common-attributes
  restart: unless-stopped

services:
  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    image: 'jc21/nginx-proxy-manager:latest'
    <<: *common-attributes
    env_file: .env
    networks:
      - media_network
    ports:
      - "80:80"      # HTTP
      - "443:443"    # HTTPS
      - "81:81"      # Admin UI
    volumes:
      - /share/CACHEDEV1_DATA/Containers/nginx-proxy-manager/data:/data
      - /share/CACHEDEV1_DATA/Containers/nginx-proxy-manager/letsencrypt:/etc/letsencrypt

  fail2ban:
    image: crazymax/fail2ban:latest
    container_name: fail2ban
    <<: *common-attributes
    cap_add:
      - NET_ADMIN
    volumes:
      - /share/CACHEDEV1_DATA/Containers/fail2ban/data:/data
      - /var/log:/var/log:ro
    networks:
      - host

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    <<: *common-attributes
    env_file: .env
    networks:
      - host
    volumes:
      - /share/CACHEDEV1_DATA/Containers/pihole/etc-pihole:/etc/pihole
      - /share/CACHEDEV1_DATA/Containers/pihole/etc-dnsmasq.d:/etc/dnsmasq.d

networks:
  media_network:
    external: true
  host:
    external: true




