x-common-attributes: &common-attributes
  restart: unless-stopped

services:
  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    image: 'jc21/nginx-proxy-manager:latest'
    <<: *common-attributes
    env_file: .env
    networks:
          - media_network
          - host
    ports:
      - "80:80"      # HTTP
      - "443:443"    # HTTPS
      - "81:81"      # Nginx Proxy Manager Admin UI
    volumes:
      - /share/CACHEDEV1_DATA/Containers/nginx-proxy-manager/data:/data
      - /share/CACHEDEV1_DATA/Containers/nginx-proxy-manager/letsencrypt:/etc/letsencrypt

  
  fail2ban:
    image: crazymax/fail2ban:latest
    container_name: fail2ban
    <<: *common-attributes
    cap_add:
      - NET_ADMIN
    volumes:
      - /share/CACHEDEV1_DATA/Containers/fail2ban/data:/data
      - /var/log:/var/log:ro
    networks:
      - host

 
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    networks:
      - media_network
    network_mode: "host"
    env_file: .env
      
    # Volumes store your data between container upgrades
    volumes:
      - /share/CACHEDEV1_DATA/Containers/pihole/etc-pihole:/etc/pihole
      - /share/CACHEDEV1_DATA/Containers/pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    # cap_add:
    #  - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    <<: *common-attributes

networks:
  media_network:
    driver: bridge
    


