x-common-attributes: &common-attributes
  restart: unless-stopped

services:
  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    image: 'jc21/nginx-proxy-manager:latest'
    <<: *common-attributes
    env_file: .env
    networks:
      - media_network
    ports:
      - "80:80"      # HTTP
      - "443:443"    # HTTPS
      - "81:81"      # Admin UI
    volumes:
      - /share/CACHEDEV1_DATA/Containers/nginx-proxy-manager/data:/data
      - /share/CACHEDEV1_DATA/Containers/nginx-proxy-manager/letsencrypt:/etc/letsencrypt

  fail2ban:
    image: crazymax/fail2ban:latest
    container_name: fail2ban
    <<: *common-attributes
    cap_add:
      - NET_ADMIN
    volumes:
      - /share/CACHEDEV1_DATA/Containers/fail2ban/data:/data
      - /var/log:/var/log:ro
      - /share/CACHEDEV1_DATA/Containers/nginx-proxy-manager/data/nginx/proxy_host:/npm-logs:ro
    network_mode: host  # ✅ only host networking
    # ❌ no `networks:` block here

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    <<: *common-attributes
    env_file: .env
    network_mode: bridge  # ✅ bridge instead of host
    ports:
      - "5380:80"            # Admin UI
      - "53443:443"          # Optional SSL
      - "5354:53/tcp"        # DNS over TCP (custom port)
      - "5354:53/udp"        # DNS over UDP (custom port)
    volumes:
      - /share/CACHEDEV1_DATA/Containers/pihole/etc-pihole:/etc/pihole
      - /share/CACHEDEV1_DATA/Containers/pihole/etc-dnsmasq.d:/etc/dnsmasq.d

networks:
  media_network:
    external: true





