version: "3"
services:
  navidrome:
    container_name: navidromev2
    image: deluan/navidrome:latest
    ports:
      - "4533:4533"
    environment:
      - PUID=1002
      - PGID=100
      - TZ=Europe/London
    volumes:
      - /share/CACHEDEV1_DATA/Containers/navidrome/config:/config
      - /share/CACHEDEV2_DATA/Photo/Music:/music
      - /share/CACHEDEV1_DATA/Containers/downloads:/downloads
      - /share/CACHEDEV1_DATA/Containers/navidrome/data:/data
    restart: on-failure
    network_mode: host

 