version: "3"

services:
  navidrome:
    container_name: navidrome
    image: deluan/navidrome:latest
    environment:
      - PUID=1002
      - PGID=100
      - TZ=Europe/London
    volumes:
      - /share/CACHEDEV1_DATA/Containers/navidrome/config:/config
      - /share/CACHEDEV2_DATA/Photo/Music:/music
      - /share/CACHEDEV1_DATA/Containers/downloads:/downloads
      - /share/CACHEDEV1_DATA/Containers/navidrome/data:/data
    expose:
      - "4533"
    restart: unless-stopped
    networks:
      - media_network

  icecast:
    image: infiniteproject/icecast
    container_name: icecast
    ports:
      - "8000:8000"
    environment:
      - PUID=1002
      - PGID=100
      - TZ=Europe/London
      - ICECAST_SOURCE_PASSWORD=sourcepass
      - ICECAST_RELAY_PASSWORD=relaypass
      - ICECAST_ADMIN_PASSWORD=adminpass
      - ICECAST_PASSWORD=listenpass
    restart: unless-stopped
    networks:
      - media_network

  liquidsoap:
    image: pltnk/liquidsoap:latest
    container_name: liquidsoap
    environment:
      - PUID=1002
      - PGID=100
      - TZ=Europe/London
    volumes:
      - /share/CACHEDEV1_DATA/Containers/liquidsoap/scripts/script.liq:/etc/liquidsoap/script.liq
      - /share/CACHEDEV2_DATA/Photo/Music:/music:ro
    depends_on:
      - icecast
    restart: unless-stopped
    networks:
      - media_network

networks:
  media_network:
    external: true
