version: "3"

services:
  navidrome:
    container_name: navidrome
    image: deluan/navidrome:latest
    environment:
      - PUID=1002
      - PGID=100
      - TZ=Europe/London
    volumes:
      - /share/CACHEDEV1_DATA/Containers/navidrome/config:/config
      - /share/CACHEDEV2_DATA/Photo/Music:/music
      - /share/CACHEDEV1_DATA/Containers/downloads:/downloads
      - /share/CACHEDEV1_DATA/Containers/navidrome/data:/data
    expose:
      - "4533"
    restart: unless-stopped
    networks:
      - media_network

  azuracast:
    container_name: azuracast
    image: azuracast/azuracast:latest
    environment:
      - AZURACAST_HTTP_PORT=8080
      - AZURACAST_HTTPS_PORT=8443
      - AUTO_ASSIGN_PORT_MIN=8010
      - AUTO_ASSIGN_PORT_MAX=8050
    volumes:
      - /share/CACHEDEV1_DATA/Containers/azuracast/stations:/var/azuracast/stations
      - /share/CACHEDEV2_DATA/Photo/Music:/var/azuracast/uploads/music
      - /share/CACHEDEV1_DATA/Containers/azuracast/data:/var/azuracast
    ports:
      - "8080:8080"     # Internal web UI (NPM will proxy this)
      - "8010-8050:8010-8050"  # Radio station stream ports
    restart: unless-stopped
    networks:
      - media_network

networks:
  media_network:
    external: true