version: "3"
services:
  navidrome:
    container_name: navidromev2
    image: deluan/navidrome:latest
    ports:
      - "4533:4533"
    environment:
      - PUID=1002
      - PGID=100
      - TZ=Europe/London
    volumes:
      - /share/CACHEDEV1_DATA/Containers/navidrome/config:/config
      - /share/CACHEDEV2_DATA/Photo/Music:/music
      - /share/CACHEDEV1_DATA/Containers/downloads:/downloads
      - /share/CACHEDEV1_DATA/Containers/navidrome/data:/data
    restart: on-failure
    network_mode: host

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfinv2
    environment:
      - PUID=1002
      - PGID=100
      - TZ=Etc/UTC
      - JELLYFIN_PublishedServerUrl=192.168.0.5 #optional
    volumes:
      - /share/CACHEDEV1_DATA/Containers/jellyfin/Config:/config
      - /share/CACHEDEV1_DATA/Containers/jellyfin/transcode:/transcode #plex
      - /share/CACHEDEV1_DATA/Containers/jellyfin/backups:/backups #plex
      - /share/CACHEDEV1_DATA/PLEX/tech:/tech

    network_mode: host
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped