version: "3"

services:
  navidrome:
    container_name: navidrome
    image: deluan/navidrome:latest
    environment:
      - PUID=1002
      - PGID=100
      - TZ=Europe/London
    volumes:
      - /share/CACHEDEV1_DATA/Containers/navidrome/config:/config
      - /share/CACHEDEV2_DATA/Photo/Music:/music
      - /share/CACHEDEV1_DATA/Containers/downloads:/downloads
      - /share/CACHEDEV1_DATA/Containers/navidrome/data:/data
    expose:
      - "4533"
    restart: unless-stopped
    networks:
      - media_network

  
networks:
  media_network:
    external: true