version: "3"

services:
  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    environment:
      - PUID=1002
      - PGID=100
      - TZ=Europe/London
    volumes:
      - /share/CACHEDEV1_DATA/Containers/tautulli/config:/config
    expose:
      - "8181"
    restart: unless-stopped
    networks:
      - media_network

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    environment:
      - PUID=1002
      - PGID=100
      - TZ=Europe/London
    volumes:
      - /share/CACHEDEV1_DATA/Containers/watchtower/config:/config
      - /var/run/docker.sock:/var/run/docker.sock
    expose:
      - "8282"
    restart: unless-stopped
    networks:
      - media_network

  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1002
      - PGID=100
      - TZ=Europe/London
    volumes:
      - /share/CACHEDEV1_DATA/Containers/heimdall/config:/config
    expose:
      - "8082"
      - "4431"
    restart: unless-stopped
    networks:
      - media_network

  ombi:
    image: linuxserver/ombi
    container_name: ombi
    environment:
      - PUID=1002
      - PGID=100
      - TZ=Europe/London
    volumes:
      - /share/CACHEDEV1_DATA/Containers/ombi/config:/config
    expose:
     - "3579"
    restart: unless-stopped
    networks:
     - media_network

  gotify:
    image: gotify/server:latest
    container_name: gotify
    environment:
      - PUID=1002
      - PGID=100
      - TZ=Europe/London      
    volumes:
      - /share/CACHEDEV1_DATA/Containers/gotify/data:/app/data
    expose:
      - "80"
    restart: unless-stopped
    networks:
      - media_network
  
  igotify:
    container_name: igotify
    hostname: igotify
    image: ghcr.io/androidseb25/igotify-notification-assist
    restart: unless-stopped
    networks:
      - media_network
    expose:
      - "8080"
    volumes:
      - api-data:/app/data
    environment:                 # option environment see above note
      - PUID=1002
      - PGID=100
      - TZ=Europe/London 
      - GOTIFY_URLS: http://gotify.alexlovett.co.uk
      - GOTIFY_CLIENT_TOKENS: CjuvhC5i27mffcH
    #  SECNTFY_TOKENS:       ''

networks:
  media_network:
    external: true