version: "3"

services:
  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulliv2
    environment:
      - PUID=1002
      - PGID=100
      - TZ=Europe/London
    volumes:
      - /share/CACHEDEV1_DATA/Containers/tautulli/config:/config
    expose:
      - "8181"
    restart: unless-stopped
    networks:
      - media_network

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    environment:
      - PUID=1002
      - PGID=100
      - TZ=Europe/London
    volumes:
      - /share/CACHEDEV1_DATA/Containers/watchtower/config:/config
      - /var/run/docker.sock:/var/run/docker.sock
    expose:
      - "8282"
    restart: unless-stopped
    networks:
      - media_network

  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1002
      - PGID=100
      - TZ=Europe/London
    volumes:
      - /share/CACHEDEV1_DATA/Containers/heimdall/config:/config
    expose:
      - "8082"
      - "4431"
    restart: unless-stopped
    networks:
      - media_network

networks:
  media_network:
    external: true