version: "3"
services:
  tautulli:
    image: linuxserver/tautulli:latest
    container_name: tautulliv2
    environment:
      - PUID=1002
      - PGID=100
      - TZ=Europe/London
    volumes:
      - /share/CACHEDEV1_DATA/Containers/tautulli/config:/config
    ports:
      - 8181:8181
    restart: on-failure
    network_mode: host

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    environment:
      - PUID=1002
      - PGID=100
      - TZ=Europe/London
    volumes:
      - /share/CACHEDEV1_DATA/Containers/watchtower/config:/config
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8282:8282
    restart: on-failure
    network_mode: host
  
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
        - /share/CACHEDEV1_DATA/Containers/nginx/config:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped

  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1002
      - PGID=100
      - TZ=Europe/London
    volumes:
      - /share/CACHEDEV1_DATA/Containers/heimdall/config:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped