version: "3"
services:
  tautulli:
    image: linuxserver/tautulli:latest
    container_name: tautulliv2
    env_file: .env
    volumes:
      - /share/CACHEDEV1_DATA/Containers/tautulli/config:/config
    labels:
      - "nginx_proxy.enable=true"
      - "nginx_proxy.domain=tautulli.alexlovett.co.uk"
      - "nginx_proxy.ssl=true"
    restart: on-failure
    networks:
      - media_network

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    env_file: .env
    volumes:
      - /share/CACHEDEV1_DATA/Containers/watchtower/config:/config
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "nginx_proxy.enable=false"
    restart: on-failure
    networks:
      - media_network
  
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    env_file: .env
    volumes:
      - /share/CACHEDEV1_DATA/Containers/heimdall/config:/config
    labels:
      - "nginx_proxy.enable=true"
      - "nginx_proxy.domain=heimdall.alexlovett.co.uk"
      - "nginx_proxy.ssl=true"
    networks:
      - media_network
    restart: unless-stopped

networks:
  media_network:
    external: true
