---
version: "2.1"
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarrv2
    environment:
      - PUID=1002
      - PGID=100
      - TZ=Europe/London
    volumes:
      - /share/CACHEDEV1_DATA/Containers/radarr/config:/config
      - /share/CACHEDEV1_DATA/PLEX/movies:/movies 
      - /share/CACHEDEV2_DATA/Photo/movies:/movies2 
      - /share/CACHEDEV2_DATA/Photo/Kids:/kidsmovies
      - /share/CACHEDEV2_DATA/Photo/xmas:/xmasmovies 
      - /share/CACHEDEV1_DATA/Containers/downloads:/downloads 
    ports: 
    - 7878:7878
    restart: on-failure
    network_mode: host
  
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarrv2
    environment:
      - PUID=1002
      - PGID=100
      - TZ=Europe/London
    volumes:
      - /share/CACHEDEV1_DATA/Containers/Sonarr/config:/config
      - /share/CACHEDEV2_DATA/Photo/Tv:/tv
      - /share/CACHEDEV2_DATA/Photo/Kids TV:/kidstv
      - /share/CACHEDEV1_DATA/Containers/downloads:/downloads 
    ports:
      - 8989:8989
    restart: on-failure
    network_mode: host
 
  nzbget:
    image: lscr.io/linuxserver/nzbget:latest
    container_name: nzbgetv2
    environment:
      - PUID=1002
      - PGID=100
      - TZ=Europe/London
    volumes:
      - /share/CACHEDEV1_DATA/Containers/NZBGet/Config:/config
      - /share/CACHEDEV1_DATA/Containers/downloads/usenet:/downloads
      - /share/CACHEDEV1_DATA/PLEX:/data
    ports:
      - 6789:6789
    restart: on-failure
    network_mode: host
  
  hydra2:
    image: linuxserver/nzbhydra2:latest
    container_name: hydra2v2
    environment:
      - PUID=1002
      - PGID=100
      - TZ=Europe/London
    volumes:
      - /share/CACHEDEV1_DATA/Containers/Hydra2/config:/config
      - /share/CACHEDEV1_DATA/Containers/downloads:/downloads
    ports:
      - 5076:5076
    restart: on-failure
    network_mode: host
  
  whisparr:
    image: docker/hotio/whisparr:latest
    container_name: whisparrv2
    environment:
      - PUID=1002
      - PGID=100
      - TZ=Europe/London
    volumes:
      - /share/CACHEDEV1_DATA/Containers/whisparr/config:/config 
      - /share/CACHEDEV1_DATA/Containers/whisparr/downloads:/downloads 
      - /share/CACHEDEV1_DATA/PLEX/tech:/tech
    ports:
      - 9696:9696
    restart: unless-stopped
    version: "3"
  
  navidrome:
    container_name: navidromev2
    image: deluan/navidrome:latest
    ports:
      - "4533:4533"
    environment:
      - PUID=1002
      - PGID=100
      - TZ=Europe/London
    volumes:
      - /share/CACHEDEV1_DATA/Containers/navidrome/config:/config
      - /share/CACHEDEV2_DATA/Photo/Music:/music
      - /share/CACHEDEV1_DATA/Containers/downloads:/downloads
      - /share/CACHEDEV1_DATA/Containers/navidrome/data:/data
    restart: on-failure
    network_mode: host

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackettv2
    environment:
      - PUID=1002
      - PGID=100
      - TZ=Europe/London
      - AUTO_UPDATE=true #optional
      - RUN_OPTS=<run options here> #optional
    volumes:
      - /share/CACHEDEV1_DATA/Containers/jackett/config:/config
      - /share/CACHEDEV1_DATA/Containers/downloads/torrents:/downloads
    ports:
      - 9117:9117
    restart: on-failure
    network_mode: host

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1002
      - PGID=100
      - TZ=Europe/London
    volumes:
      - /share/CACHEDEV1_DATA/Containers/lidarr/config:/config
      - /share/CACHEDEV2_DATA/Photo/Music:/music
      - /share/CACHEDEV1_DATA/Containers/downloads:/downloads
    ports:
      - 8686:8686
    restart: on-failure
    network_mode: host

    version: "2.1"

  organizr:
    image: organizr/organizr:latest
    container_name: organizrv2
    environment:
      - PUID=1002
      - PGID=100
      - TZ=Europe/London
    volumes:
      - /share/CACHEDEV1_DATA/Containers/organizr/config:/config 
    ports: 
    - 6262:6262
    restart: on-failure
    network_mode: host

  plex:
    container_name: plexv2
    image: lscr.io/linuxserver/plex:latest
    restart: on-failure
    environment:
      - PUID=1002
      - PGID=100
      - TZ=Europe/London
      - PLEX_CLAIM=rR4u9BRDGq1_DXUQTy92&X
    network_mode: host
    volumes:
      - /share/CACHEDEV1_DATA/Containers/plex/Config:/config
      - /share/CACHEDEV1_DATA/Containers/plex/transcode:/transcode
      - /share/CACHEDEV1_DATA/Containers/plex/backups:/backups
      - /share/CACHEDEV2_DATA/Photo/Tv:/Tv
      - /share/CACHEDEV2_DATA/Photo/Kids TV:/kidstv
      - /share/CACHEDEV1_DATA/PLEX/movies:/movies 
      - /share/CACHEDEV2_DATA/Photo/Kids:/kidsmovies 
      - /share/CACHEDEV2_DATA/Photo/xmas:/xmasmovies 
      - /share/CACHEDEV2_DATA/Photo/Home Movies:/homemovies
      - /share/CACHEDEV2_DATA/Photo/Photos:/photos
      - /share/CACHEDEV2_DATA/Photo/Music:/music
    ports:
      - 32400:32400

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarrv2
    environment:
      - PUID=1002
      - PGID=100
      - TZ=Europe/London
    volumes:
      - /share/CACHEDEV1_DATA/Containers/prowlarr/config:/config 
      - /share/CACHEDEV1_DATA/Containers/prowlarr/Queued:/downloads 
    ports:
      - 9696:9696
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrentv2
    environment:
      - PUID=1002
      - PGID=100
      - TZ=Europe/London
      - WEBUI_PORT=8080
    volumes:
      - /share/CACHEDEV1_DATA/Containers/qbitorrent/config:/config
      - /share/CACHEDEV1_DATA/Containers/downloads/torrents:/downloads
      - /share/CACHEDEV1_DATA/Containers/qbitorrent/watch:/watch
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080
    restart: on-failure
  
  tautulli:
    image: linuxserver/tautulli
    container_name: tautulliv2
    environment:
      - PUID=1002
      - PGID=100
      - TZ=Europe/London
    volumes:
      - /share/CACHEDEV1_DATA/Containers/tautulli/config:/config
    ports:
      - 8181:8181
    restart: on-failure
    network_mode: host

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfinv2
    environment:
      - PUID=1002
      - PGID=100
      - TZ=Etc/UTC
      - JELLYFIN_PublishedServerUrl=192.168.0.5 #optional
    volumes:
      - /share/CACHEDEV1_DATA/Containers/jellyfin/Config:/config
      - /share/CACHEDEV1_DATA/Containers/jellyfin/transcode:/transcode #plex
      - /share/CACHEDEV1_DATA/Containers/jellyfin/backups:/backups #plex
      - /share/CACHEDEV1_DATA/PLEX/tech:/tech

    network_mode: host
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped

