version: '3.9'
services:

  # ##
  # Default username = admin
  # Default password = admin
  # ##
  grafana:
    container_name: grafana
    hostname: grafana
    image: grafana/grafana:latest
    restart: always
    privileged: true
    stdin_open: true
    tty: true
    depends_on:
      - influxdb
    ports:
      - 3000:3000
    environment:
      - PUID=1002
      - PGID=100
      - TZ=Europe/London
    volumes:
      - /share/CACHEDEV1_DATA/Containers/grafana/config:/config
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

  influxdb:
    container_name: influxdb
    hostname: influxdb
    image: arm32v7/influxdb:latest
    restart: always
    privileged: true
    stdin_open: true
    tty: true
    volumes:
      - /share/CACHEDEV1_DATA/Containers/influxdb/:influxdb
      - /share/CACHEDEV1_DATA/Containers/influxdb/data/:data
      - /share/CACHEDEV1_DATA/Containers/influxdb/wal/:wal
      - /share/CACHEDEV1_DATA/Containers/influxdb/meta/:meta
    ports:
      - 8083:8083
      - 8086:8086
      - 25826:25826
    environment:
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=password
      - INFLUXDB_DB=pidb
      - PUID=1002
      - PGID=100
      - TZ=Europe/London
    logging:
      driver: "json-file"
      options:
        max-size: "50m"