version: "2.1"
services:
  hydra2:
    image: linuxserver/hydra2
    container_name: hydra2
    environment:
      - PUID=1002
      - PGID=100
      - TZ=Europe/London
    volumes:
      - /share/CACHEDEV1_DATA/Containers/Hydra2/config:/config
      - /share/CACHEDEV1_DATA/Containers/downloads:/downloads
    ports:
      - 5076:5076
    restart: on-failure
    network_mode: host