---
version: "2.1"
services:
  jackett:
    image: lscr.io/linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1002
      - PGID=100
      - TZ=Europe/London
      - AUTO_UPDATE=true #optional
      - RUN_OPTS=<run options here> #optional
    volumes:
      - /share/CACHEDEV1_DATA/Containers/jackett/config:/config
      - /share/CACHEDEV1_DATA/Containers/downloads/toreents:/downloads
    ports:
      - 9117:9117
    restart: on-failure
    network_mode: host