version: "2.1"
services:
  radarr:
    image: organizr/organizr
    container_name: organizr
    environment:
      - PUID=1002
      - PGID=100
      - TZ=Europe/London
    volumes:
      - /home/organizr:/share/Containers/organizr/config 
     
    ports: 
    - 6262:6262
    restart: on-failure
    network_mode: host