version: '2.1'
services:
  plex:
    container_name: plex
    image: lscr.io/linuxserver/plex:latest
    restart: on-failure
    environment:
      - PUID=1002
      - PGID=100
      - TZ=Europe/London
      - PLEX_CLAIM=rR4u9BRDGq1_DXUQTy92&X
    network_mode: host
    volumes:
      - /share/CACHEDEV1_DATA/Containers/plex/Config:/config
      - /share/CACHEDEV1_DATA/Containers/plex/transcode:/transcode
      - /share/CACHEDEV1_DATA/Containers/plex/backups:/backups
      - /share/CACHEDEV2_DATA/Photo/Tv:/Tv
      - /share/CACHEDEV2_DATA/Photo/Kids TV:/kidstv
      - /share/CACHEDEV1_DATA/PLEX/movies:/movies 
      - /share/CACHEDEV2_DATA/Photo/Kids:/kidsmovies 
      - /share/CACHEDEV2_DATA/Photo/xmas:/xmasmovies 
      - /share/CACHEDEV2_DATA/Photo/Home Movies:/homemovies
      - /share/CACHEDEV2_DATA/Photo/Photos:/photos
      - /share/CACHEDEV2_DATA/Photo/Music:/music
    ports:
      - 32400:32400