---
version: "2.1"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1002
      - PGID=100
      - TZ=Europe/London
      - WEBUI_PORT=8080
    volumes:
      - /share/CACHEDEV1_DATA/Containers/qbitorrent/config:/config
      - /share/CACHEDEV1_DATA/Containers/downloads/torrents:/downloads
      - /share/CACHEDEV1_DATA/Containers/qbitorrent/watch:/watch
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080
    restart: on-failure