---
version: "2.1"
services:
  transmission:
    image: lscr.io/linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1002
      - PGID=100
      - TZ=Europe/London
      - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
      - USER=username #optional
      - PASS=password #optional
      - WHITELIST=iplist #optional
      - HOST_WHITELIST=dnsnane list #optional
    volumes:
      - /share/CACHEDEV1_DATA/Containers/transmission/config:/config
      - /share/CACHEDEV1_DATA/Containers/transmission/downloads:/downloads
      - /share/CACHEDEV1_DATA/Containers/transmission/watch:/watch
    network_mode: host
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: on-failure