---
version: "2.1"
services:
  whisparr:
    image: docker/hotio/whisparr:latest
    container_name: whisparr
    environment:
      - PUID=1002
      - PGID=100
      - TZ=Europe/London
    volumes:
      - /Containers/whisparr/config:/config 
      - /Containers/whisparr/downloads:/downloads 
      - /share/CACHEDEV1_DATA/PLEX/tech:/tech
    ports:
      - 9696:9696
    restart: unless-stopped